"""fix_business_currency_columns

Revision ID: 092c951f8091
Revises: a86fda970d37
Create Date: 2025-09-01 06:21:07.480858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092c951f8091'
down_revision = 'a86fda970d37'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_businesses_currency_code_currencies'), 'businesses', 'currencies', ['currency_code'], ['code'])
    op.drop_column('businesses', 'currency_symbol')
    op.drop_column('businesses', 'currency_format')
    op.drop_column('businesses', 'decimal_places')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('decimal_places', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('currency_format', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('currency_symbol', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_businesses_currency_code_currencies'), 'businesses', type_='foreignkey')
    # ### end Alembic commands ###
