"""add_barcode_scan_events_table

Revision ID: 0c1ad7e1cf6a
Revises: a7579b9b26ef
Create Date: 2025-09-07 12:56:55.864710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c1ad7e1cf6a'
down_revision = 'a7579b9b26ef'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses_backup')
    op.add_column('expenses', sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('expenses', sa.Column('original_currency_code', sa.String(length=3), nullable=False))
    op.add_column('expenses', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True))
    op.alter_column('users', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('expenses', 'exchange_rate')
    op.drop_column('expenses', 'original_currency_code')
    op.drop_column('expenses', 'original_amount')
    op.create_table('expenses_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('receipt_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recurrence_interval', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
