"""add_business_id_to_sales

Revision ID: 32e199b69446
Revises: 67a442cbc70c
Create Date: 2025-09-20 07:46:33.789554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e199b69446'
down_revision = '67a442cbc70c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_sales_business_id_businesses', 'sales', 'businesses', ['business_id'], ['id'])

    # Set default business_id for existing sales (use business_id from the user who made the sale)
    op.execute("""
        UPDATE sales
        SET business_id = users.business_id
        FROM users
        WHERE sales.user_id = users.id
    """)

    # Now make the column NOT NULL after populating it
    op.alter_column('sales', 'business_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sales_business_id_businesses', 'sales', type_='foreignkey')
    op.drop_column('sales', 'business_id')
    # ### end Alembic commands ###
