"""add_exchange_rate_to_sale_items

Revision ID: 582cb25b29dd
Revises: ce1426e9dc0d
Create Date: 2025-09-14 22:20:21.086970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582cb25b29dd'
down_revision = 'ce1426e9dc0d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
