"""add_currency_and_business_to_expenses

Revision ID: 5d840f2542e5
Revises: 092c951f8091
Create Date: 2025-09-01 07:08:15.275503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d840f2542e5'
down_revision = '092c951f8091'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('expenses', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_expenses_business_id_businesses'), 'expenses', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(op.f('fk_expenses_currency_code_currencies'), 'expenses', 'currencies', ['currency_code'], ['code'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_expenses_currency_code_currencies'), 'expenses', type_='foreignkey')
    op.drop_constraint(op.f('fk_expenses_business_id_businesses'), 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'business_id')
    op.drop_column('expenses', 'currency_code')
    # ### end Alembic commands ###
