"""add_cost_price_to_products

Revision ID: 61ea0b2e0633
Revises: f5328394d87e
Create Date: 2025-09-08 15:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Float

# revision identifiers, used by Alembic.
revision = '61ea0b2e0633'
down_revision = 'f5328394d87e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to make cost_price nullable ###
    op.add_column('products', sa.Column('cost_price', Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
