"""add_local_currency_fields_to_expense

Revision ID: 6941fa418193
Revises: 9749a44864c1
Create Date: 2025-09-10 00:33:12.127588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6941fa418193'
down_revision = '9749a44864c1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
