"""add_currency_context_to_products

Revision ID: 6fa6492b4566
Revises: 6941fa418193
Create Date: 2025-09-10 06:54:23.541607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa6492b4566'
down_revision = '6941fa418193'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('original_currency_code', sa.String(length=3), nullable=True))
    op.add_column('products', sa.Column('exchange_rate_at_creation', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'exchange_rate_at_creation')
    op.drop_column('products', 'original_currency_code')
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###
