"""Add virtual numbering to inventory history

Revision ID: 8eba80a2e6ac
Revises: d3b2583a5d8d
Create Date: 2025-09-26 20:43:36.578162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eba80a2e6ac'
down_revision = 'd3b2583a5d8d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_history', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('inventory_history', sa.Column('business_inventory_number', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_inventory_history_business_id_businesses'), 'inventory_history', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inventory_history_business_id_businesses'), 'inventory_history', type_='foreignkey')
    op.drop_column('inventory_history', 'business_inventory_number')
    op.drop_column('inventory_history', 'business_id')
    # ### end Alembic commands ###
