"""add_original_fields_to_sale_items

Revision ID: 9aa6020251dd
Revises: ec3a4dac596d
Create Date: 2025-09-12 08:32:31.807499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa6020251dd'
down_revision = 'ec3a4dac596d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('original_unit_price', sa.Float(), nullable=True))
    op.add_column('sale_items', sa.Column('original_subtotal', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'original_subtotal')
    op.drop_column('sale_items', 'original_unit_price')
    # ### end Alembic commands ###
