"""refactor_expense_currency_storage

Revision ID: b2214e934633
Revises: 1b771ce30d42
Create Date: 2025-09-05 21:05:17.471366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2214e934633'
down_revision = '1b771ce30d42'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the new columns as NULLABLE first
    op.add_column('expenses', sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('original_currency_code', sa.String(length=3), nullable=True))
    
    # Step 2: Data Migration - Populate the new columns for existing rows
    # For now, set original values to match the current (incorrect) amount/currency.
    # We will convert these to USD in a separate, dedicated data migration script.
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE expenses 
        SET original_amount = amount, 
            original_currency_code = currency_code
    """))
    
    # Step 3: Now alter the columns to be NOT NULL
    op.alter_column('expenses', 'original_amount', nullable=False)
    op.alter_column('expenses', 'original_currency_code', nullable=False)
    
    # Step 4: Now we can safely drop the currency_code column
    op.drop_constraint('fk_expenses_currency_code_currencies', 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'currency_code')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('expenses', sa.Column('currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_expenses_currency_code_currencies'), 'expenses', 'currencies', ['currency_code'], ['code'])
    op.drop_column('expenses', 'original_currency_code')
    op.drop_column('expenses', 'original_amount')
    # ### end Alembic commands ###
