"""add_exchange_rate_to_sale_items_model

Revision ID: b413554f3fb6
Revises: 582cb25b29dd
Create Date: 2025-09-14 22:24:27.883382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b413554f3fb6'
down_revision = '582cb25b29dd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('exchange_rate_at_creation', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'exchange_rate_at_creation')
    # ### end Alembic commands ###
