"""add_historical_context_to_payments

Revision ID: ce1426e9dc0d
Revises: 10141a9b4a7f
Create Date: 2025-09-14 17:17:24.914974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1426e9dc0d'
down_revision = '10141a9b4a7f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('original_amount', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('original_currency_code', sa.String(length=3), nullable=True))
    op.add_column('payments', sa.Column('exchange_rate_at_payment', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'exchange_rate_at_payment')
    op.drop_column('payments', 'original_currency_code')
    op.drop_column('payments', 'original_amount')
    # ### end Alembic commands ###
