"""add_original_cost_price_to_products

Revision ID: d762ab157918
Revises: 6fa6492b4566
Create Date: 2025-09-10 08:18:48.624347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd762ab157918'
down_revision = '6fa6492b4566'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
