"""add_currency_context_to_refunds

Revision ID: ec3a4dac596d
Revises: 246867f1fc98
Create Date: 2025-09-11 22:47:15.277669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3a4dac596d'
down_revision = '246867f1fc98'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('original_amount', sa.Float(), nullable=True))
    op.add_column('refunds', sa.Column('original_currency', sa.String(length=3), nullable=True))
    op.add_column('refunds', sa.Column('exchange_rate_at_refund', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refunds', 'exchange_rate_at_refund')
    op.drop_column('refunds', 'original_currency')
    op.drop_column('refunds', 'original_amount')
    # ### end Alembic commands ###
