"""add_two_factor_fields_to_user_model

Revision ID: 0b88dcf53d04
Revises: da2cf4fce2cb
Create Date: 2025-08-24 17:13:42.974547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b88dcf53d04'
down_revision = 'da2cf4fce2cb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('two_factor_backup_codes', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.drop_column('users', 'two_factor_backup_codes')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
