"""add_original_cost_price_to_products

Revision ID: 0c9d729eaefc
Revises: d762ab157918
Create Date: 2025-09-10 08:23:49.030982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9d729eaefc'
down_revision = 'd762ab157918'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_cost_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'original_cost_price')
    # ### end Alembic commands ###
