"""add_usd_amounts_to_sales

Revision ID: 246867f1fc98
Revises: 0c9d729eaefc
Create Date: 2025-09-11 07:41:52.401381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246867f1fc98'
down_revision = '0c9d729eaefc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('usd_amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('usd_tax_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'usd_tax_amount')
    op.drop_column('sales', 'usd_amount')
    # ### end Alembic commands ###
