"""create_barcode_scan_events_table

Revision ID: 289dc741a653
Revises: 0c1ad7e1cf6a
Create Date: 2025-09-07 12:56:55.864710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '289dc741a653'
down_revision = '0c1ad7e1cf6a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_scan_events_barcode'), 'barcode_scan_events', ['barcode'], unique=False)
    op.create_index(op.f('ix_barcode_scan_events_id'), 'barcode_scan_events', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barcode_scan_events_id'), table_name='barcode_scan_events')
    op.drop_index(op.f('ix_barcode_scan_events_barcode'), table_name='barcode_scan_events')
    op.drop_table('barcode_scan_events')
    # ### end Alembic commands ###
