"""add_refund_system

Revision ID: 696a17c0f9f4
Revises: 5a5a5a5a5a5a
Create Date: 2025-08-29 16:42:01.479510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696a17c0f9f4'
down_revision = '5a5a5a5a5a5a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_refunds_sale_id_sales')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refunds_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_table('refund_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.Integer(), nullable=True),
    sa.Column('sale_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name=op.f('fk_refund_items_refund_id_refunds')),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], name=op.f('fk_refund_items_sale_item_id_sale_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_items'))
    )
    op.create_index(op.f('ix_refund_items_id'), 'refund_items', ['id'], unique=False)
    op.add_column('sale_items', sa.Column('refunded_quantity', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('sale_items', 'refunded_quantity')
    op.drop_index(op.f('ix_refund_items_id'), table_name='refund_items')
    op.drop_table('refund_items')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
