"""add_inventory_features

Revision ID: b033bf6622da
Revises: a65cf16fc051
Create Date: 2025-08-19 20:52:46.462140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b033bf6622da'
down_revision = 'a65cf16fc051'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
