"""add_currency_fields_to_business

Revision ID: c2cf03c62eb5
Revises: 29048593ed86
Create Date: 2025-08-31 22:06:20.493066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cf03c62eb5'
down_revision = '29048593ed86'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('businesses', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('businesses', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('businesses', sa.Column('currency_symbol', sa.String(length=5), nullable=True))
    op.add_column('businesses', sa.Column('decimal_places', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('currency_format', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'currency_format')
    op.drop_column('businesses', 'decimal_places')
    op.drop_column('businesses', 'currency_symbol')
    op.drop_column('businesses', 'currency_code')
    op.drop_column('businesses', 'country_code')
    op.drop_column('businesses', 'country')
    # ### end Alembic commands ###
