"""create_rbac_tables

Revision ID: d8bd41c0288d
Revises: 49a2cb5eee28
Create Date: 2025-08-31 06:52:01.170686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bd41c0288d'
down_revision = '49a2cb5eee28'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
